### ISSUE TITLE
H3 error when building nuxt module

### ISSUE THREAD

**Issue by Baroshem** [unjs/h3#353]
### Environment

Node: 16.14
npm: 8.3.1
package-manager: yarn
nuxt: 3.2.3
nuxt-security: 0.11.0 -> Aiming to publish 0.12.0 but cannot due to this error

### Reproduction

Run `yarn prepack` in https://github.com/Baroshem/nuxt-security

### Describe the bug

After running `yarn prepack` to build a module following appears:

![image](https://user-images.githubusercontent.com/37120330/223455339-f12fa89e-7133-4c63-8460-a67dbaa7fd69.png)

### Additional context

It seems to be pointing to:

```ts
import * as ufo from 'ufo';
``` 

in node_modules/h3/dist/index.d.ts

### Logs

```sh
SyntaxError: Unexpected token (7:5) in /Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/h3/dist/index.d.ts
    at Object.pp$4.raise (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:20009:13)
    at Object.pp$9.unexpected (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:17310:8)
    at Object.pp$9.semicolon (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:17287:66)
    at Object.pp$8.parseExpressionStatement (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:17770:8)
    at Object.pp$8.parseStatement (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:17503:24)
    at Object.pp$8.parseTopLevel (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:17367:21)
    at Object.parse (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:17139:15)
    at Function.parse (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:17189:35)
    at Graph.contextParse (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/rollup/dist/es/shared/rollup.js:23503:38)
    at tryParse (file:///Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/unbuild/node_modules/@rollup/plugin-commonjs/dist/es/index.js:17:12) {
  pos: 316,
  loc: {
    column: 5,
    file: '/Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/h3/dist/index.d.ts',
    line: 7
  },
  raisedAt: 328,
  frame: "5: import * as ufo from 'ufo';\n" +
    '6: \n' +
    '7: type SessionDataT = Record<string, any>;\n' +
    '        ^\n' +
    '8: type SessionData<T extends SessionDataT = SessionDataT> = T;\n' +
    '9: interface Session<T extends SessionDataT = SessionDataT> {',
  id: '/Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/h3/dist/index.d.ts',
  hook: 'resolveId',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  watchFiles: [
    '/Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/src/module.ts',
    '/Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/src/types.ts',
    '/Users/jakubandrzejewski/Coding/open-source/nuxt/nuxt-security/node_modules/h3/dist/index.d.ts'
  ]
}
error Command failed with exit code 1.
```
```

**Comment by Baroshem** [comment]
I just recently migrated h3-cors package to native CORS in H3, maybe this can be a cause of the issue?

**Comment by Baroshem** [comment]
Hey @pi0 

Do you have any idea about this bug?

It stopps me from releasing a new version of the Security module :(

**Comment by Baroshem** [comment]
I managed to find a solution. 

Basically, I cannot import files from `h3` in the `module.ts` file in Nuxt module. I created types locally to fix this.

**Comment by NozomuIkuta** [comment]
@Baroshem 

Seeing the error message, you might have been facing at https://github.com/unjs/unbuild/issues/135.

At the moment, unfortunately, there seems to be no way to fix it or provide workaround on user side, because nuxt module builder accepts just few of unbuild options from user ([ref](https://github.com/nuxt/module-builder/blob/844e8ddf598cf9835c250a77f6452433e3678d49/src/build.ts#L8-L12)).

**Comment by Baroshem** [comment]
Thanks for clarification @NozomuIkuta ! I managed to fix it by not using the types from h3 in my module
