### ISSUE TITLE
readMultipartFormData method error on Netlify

### ISSUE THREAD

**Issue by besscroft** [unjs/h3#590]
### Environment

Node Version: v18.18.0

### Reproduction

https://github.com/besscroft/kamera/blob/dev/server/api/uploadFile.post.ts

### Describe the bug

When I requested this interface, an error message appeared. I'm running fine on Windows 11 and Vercel, but I'm getting errors with Netlify.

```ts
export default defineEventHandler(async (event) => {
    const body = await readMultipartFormData(event)
    console.log('body', body)
})
```

On Windows 11 and Vercel, body gets the correct content, but on Netlify, body is []. I tried a few things but couldn't solve the problem.

Finally, thank you for taking the time to read my question, thank you!

### Additional context

I think the problem lies here: [return parseMultipartData(body, boundary);](https://github.com/unjs/h3/blob/afc4183b513d517bbe83449f1a3dd5291f230e6c/src/utils/body.ts#L228)
![`ORH W8S 5RMYUI$MH0BJ}V](https://github.com/unjs/h3/assets/33775809/523f919e-1bd2-4b79-bd9a-9032cffde8a4)

### Logs

```sh
Dec 4, 10:03:40 PM: d6a18e95 INFO   contentType multipart/form-data; boundary=----WebKitFormBoundaryxFcO1w3Pn2alJ4z3
Dec 4, 10:03:40 PM: d6a18e95 INFO   boundary ----WebKitFormBoundaryxFcO1w3Pn2alJ4z3
Dec 4, 10:03:40 PM: d6a18e95 INFO   rawBody <Buffer 4c 53 30 74 4c 53 30 74 56 32 ......
Dec 4, 10:03:40 PM: d6a18e95 INFO   body []
Dec 4, 10:03:40 PM: d6a18e95 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'data')
Dec 4, 10:03:40 PM: d6a18e95 ERROR    at ./chunks/uploadFile.post.mjs:37:24
Dec 4, 10:03:40 PM: d6a18e95 ERROR    at async Object.handler (./chunks/nitro/netlify.mjs:2444:19)
Dec 4, 10:03:40 PM: d6a18e95 ERROR    at async toNodeHandle (./chunks/nitro/netlify.mjs:2633:7)
Dec 4, 10:03:40 PM: d6a18e95 ERROR    at async lambda (./chunks/nitro/netlify.mjs:5604:13)
```

**Comment by BenGoetemann** [comment]
I have the same issue...

**Comment by fadeaway** [comment]
> I have the same issue... Locally everything works fine, but I log an empty array on netlify.

I get the same thing you are getting. It works fine locally when I deploy to cloudflare it's just an empty array.

**Comment by yocheved** [comment]
Is there a solution to this problem I'm also having the same issue. What can I use instead?

**Comment by fadeaway** [comment]
> Is there a solution to this problem I'm also having the same issue. What can I use instead?

possibly NuxtHub blob?

**Comment by kricsleo** [comment]
Cannot reproduce.

You may check this example: https://github.com/kricsleo/repro-h3-590
(I copied your package.json and lock file, so the dependencies should be the same.)

Deployed on vercel: https://repro-h3-590.vercel.app

It successfully parsed the body and returned the expected result.

**Comment by kricsleo** [comment]
Cannot reproduce.

You may check this example: https://github.com/kricsleo/repro-h3-590
(I copied your package.json and lock file, so the dependencies should be the same.)

Deployed on vercel: https://repro-h3-590.vercel.app

It successfully parsed the body and returned the expected result.

<img width="1229" alt="Image" src="https://github.com/user-attachments/assets/ea737084-73b5-4963-a7c3-00c58cdef117" />

**Comment by pi0** [comment]
(closing as there is lack of reproduction)
