### ISSUE TITLE
`sendRedirect` and `send` send headers before `onBeforeResponse` hook is called

### ISSUE THREAD

**Issue by vejja** [unjs/h3#596]
### Environment

nuxt 3.8.2
nuxt-security 1.0.0-rc.5
node 18.18.0

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ad78lc?file=package.json

- Go to `/go/google` page in the application
- Observe error in the server console logs (in Stackblitz)

### Describe the bug

When using the `sendRedirect` method in a server handler:
- the server handler sends the response headers without waiting for the Nitro `beforeResponse` hook
- when the `beforeResponse` hook is called, if that hook tries to modify the headers it is too late 

The stackblitz repro uses Nuxt-Security as its sole module dependency.
Nuxt-Security implements a Nitro `beforeResponse` hook that is designed to hide the identity of the server by suppressing the `X-Powered-By` header.
The error is generated in the repro because the `go/google` route implements the `sendRedirect` method.

### Additional context

Hi, Nuxt Security team here.

#### Original Issue
This issue was initially reported in [Nuxt Security](https://github.com/Baroshem/nuxt-security/issues/315).
The user is reporting that when a server route uses `sendRedirect`, Nitro reports the following error:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
```

#### Bug context

After investigation, it appears that our module is responsible for the error when it tries to suppress the 'X-Powered-By' HTTP header. 
We indeed suppress that header via a Nitro plugin with the following code:
```ts
import { defineNitroPlugin, removeResponseHeader } from '#imports'
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('beforeResponse', (event) => {
    removeResponseHeader(event, 'x-powered-by')
  })
})
```

On their end, OP have implemented custom logic to redirect a user request via a server handler:
```ts
export default defineEventHandler(event => {
  return sendRedirect(event, 'https://google.com')
})
```

#### Conclusion

Our Nitro plugin specifically uses the `beforeResponse` hook.
However the OP's server handler sends the response's redirect headers before our Nitro plugin is invoked.

### Logs

```sh
Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at __node_internal_ (https://nuxtstarterad78lc-a5of.w-credentialless.staticblitz.com/blitz.d3416dfd.js:36:5406)
    at new <anonymous> (https://nuxtstarterad78lc-a5of.w-credentialless.staticblitz.com/blitz.d3416dfd.js:36:4168)
    at OutgoingMessage.removeHeader (https://nuxtstarterad78lc-a5of.w-credentialless.staticblitz.com/blitz.d3416dfd.js:184:9907)
    at Module.removeResponseHeader (file:///home/projects/nuxt-starter-ad78lc/node_modules/h3/dist/index.mjs:868:25)
    at eval (file:///home/projects/nuxt-starter-ad78lc/.nuxt/dev/index.mjs:813:76)
    at eval (file:///home/projects/nuxt-starter-ad78lc/node_modules/hookable/dist/index.mjs:68:66)
    at Object.run (file:///home/projects/nuxt-starter-ad78lc/node_modules/hookable/dist/index.mjs:61:43)
    at eval (file:///home/projects/nuxt-starter-ad78lc/node_modules/hookable/dist/index.mjs:68:56)
    at async Object.onBeforeResponse (file:///home/projects/nuxt-starter-ad78lc/.nuxt/dev/index.mjs:1342:7)
    at async Object.eval [as handler] (file:///home/projects/nuxt-starter-ad78lc/node_modules/h3/dist/index.mjs:1754:11)
    at async Server.toNodeHandle (file:///home/projects/nuxt-starter-ad78lc/node_modules/h3/dist/index.mjs:1959:7) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by pi0** [comment]
Thanks for reporting this. Indeed it is an unwanted behavior because `sendRedirect` (and other `send*` utils) the way they are implemented, they immediately call Node.js send method bypassing h3's lifecycle.

While we could kinda fix it by avoiding `send` and instead returning HTML in utils, it can be also a breaking change for users that don't use `return sendRedirect`. 

I am thinking to find a balanced solution for this to allow differed sends even if users forget but might be delayed until next Minor as is more than a fix.

**Comment by pi0** [comment]
With upcoming h3 v2 send is direct and last step so this should not be an issue anymore.
