### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zach-at-healthpilot** [unjs/h3#61]
I'm getting an error when I try to use nuxi and @nuxt/bridge-edge to run a server; the error appears to be on `layer.handle.length` if `layer.handle` is undefined

using
`    "@nuxt/bridge": "@nuxt/bridge-edge@3.0.0-27303090.f5d1d9a",`
`node v14.18.0`

```sh
 FATAL  Cannot read property 'length' of undefined

at normalizeLayer ([app]/node_modules/h3/dist/index.mjs:625:36)
at use ([app]/node_modules/h3/dist/index.mjs:580:20)
at Function.app.use ([app]/node_modules/h3/dist/index.mjs:567:35)
at createDevServer ([app]/node_modules/@nuxt/nitro/dist/index.mjs:1796:7)
at createNuxt2DevServer ([app]/node_modules/@nuxt/bridge-edge/dist/chunks/module.mjs:269:18)
at setupNitroBridge ([app]/node_modules/@nuxt/bridge-edge/dist/chunks/module.mjs:163:19)
at setup ([app]/node_modules/@nuxt/bridge-edge/dist/chunks/module.mjs:1054:13)
at ModuleContainer.normalizedModule ([app]/node_modules/@nuxt/kit/dist/index.mjs:501:29)
```

```mjs
// file ([app]/node_modules/h3/dist/index.mjs:625:36)

function normalizeLayer(layer) {
  if (layer.promisify === void 0) {
    layer.promisify = layer.handle.length > 2;
  }
  return {
    route: withoutTrailingSlash(layer.route),
    match: layer.match,
    handle: layer.lazy ? lazyHandle(layer.handle, layer.promisify) : layer.promisify ? promisifyHandle(layer.handle) : layer.handle
  };
}
```

```

**Comment by danielroe** [comment]
closing to follow here: https://github.com/nuxt/framework/issues/2790
