### ISSUE TITLE
h3-session: ERROR  [nuxt] [request error] [unhandled] [500] Cannot set properties of undefined (setting 'content-type')

### ISSUE THREAD

**Issue by BananaAcid** [unjs/h3#770]
### Environment

In Node v20.14-latest
Nuxt: Nuxt 3.11.2 and 3.12.1
on MacOS and Ubuntu

Nuxt Modules: @vueuse/nuxt
Vuetify installed as defined on their homepage

### Reproduction

I have no idea, where this came from. When removing `SSR: false` it showed up, at the end of a long development.

### Describe the bug

Nuxt shows: `TypeError: Cannot set properties of undefined (setting 'content-type')` on the website.

the Console shows:
```
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot set properties of undefined (setting 'content-type')
  at ServerResponse.setHeader (node:_http_outgoing:712:45)  
  at setResponseHeaders (./node_modules/h3/dist/index.mjs:778:20)  
  at Object.handler (./node_modules/nitropack/dist/runtime/renderer.mjs:31:7)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./node_modules/h3/dist/index.mjs:1962:19  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at errorhandler (./node_modules/nuxt/dist/core/runtime/nitro/error.js:37:41)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2256:9)
```

Nothing else.

### Additional context

I never set `content-type` anywhere.

Is this a known thing?

Anything specific could search the code for?

**Comment by pi0** [comment]
Without reproduction, it is really not possible to tell. If you have same issue still and can assemble a repo (nuxt app) would be happy to track here.

**Comment by AbingLeo-ideahub** [comment]
i got same issue
"TypeError: Cannot set properties of undefined (setting 'content-type')"

if i set the node express in server/middleware folder.
