### ISSUE TITLE
0.5.4 problems with nuxt3

### ISSUE THREAD

**Issue by andysay** [unjs/h3#83]
/.output/server/chunks/nitro/server.mjs:69
const hasReqHeader = (req, header, includes) => req.headers[header] && req.headers[header].toLowerCase().includes(includes);
                                                           ^

TypeError: Cannot read properties of undefined (reading 'accept')
    at hasReqHeader (file:///home/garant/admin/.output/server/chunks/nitro/server.mjs:69:60)
    at Object.handleError [as onError] (file:///home/garant/admin/.output/server/chunks/nitro/server.mjs:71:25)
    at nodeHandler (file:///home/garant/admin/.output/server/node_modules/h3/dist/index.mjs:319:23)

**Comment by pi0** [comment]
Do you mind to share a reproduction and open issue in Nuxt 3 repository instead?

**Comment by andysay** [comment]
> Do you mind to share a reproduction and open issue in Nuxt 3 repository instead?

i'm try find where is it.

**Comment by hajime9652** [comment]
@andysay I had a same error with wrong version of h3 in package.json
