### ISSUE TITLE
readMultipartFormData error when parsing big files

### ISSUE THREAD

**Issue by GuppyTheCat** [unjs/h3#851]
### Environment

node.js: 22.4.1
nuxt: 3.12.4
primevue: 3.53.0
vue: 3.4.34

### Reproduction

Here is repo - [file-upload-test](https://github.com/GuppyTheCat/file-upload-test)
On button click you choose file and upload should automatically start.

### Describe the bug

I have nuxt3 application.
I send file from nuxt3 frontend to nuxt3 server api.
If i send file approximately larger than 100Mb then i get this error while parsing multipart from data:
```
Error reading multipart form data: Invalid array length

  at Array.push (<anonymous>)
  at parse (node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:196:16)
  at readMultipartFormData (node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:469:10)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at Object.handler (server/api/upload.post.ts:4:1)
  at async node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:19
  at async Object.callAsync (node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)``````


### Additional context

_No response_

### Logs

_No response_

**Comment by s3xysteak** [comment]
Hi Guppy, it looks like it will be fixed in v2. #514

**Comment by moshetanzer** [comment]
Ahh. No! There definitely are ways to do with other kind I ended up using `busboy` and can also be done with `formidable`, was more asking a way to do this without another lib or some sort of simple patch!

**Comment by productdevbook** [comment]
@pi0 I want to work on this for v2. Can we do it only for v2?

**Comment by paranoidPhantom** [comment]
I can confirm this is an issue I am also experiencing

**Comment by NikhilVerma** [comment]
This is the workaround I've been using so far that works for large files for me

```ts
/**
 * Parse multipart data using streaming to avoid h3's array length limits
 */
async function parseMultipartData(
	event: H3Event,
	contentType: string
): Promise<Array<{ name: string; data: Buffer; filename?: string }>> {
	try {
		// Read with streaming to avoid array length limits
		const chunks: Array<Buffer> = [];
		const { req } = event.node;

		for await (const chunk of req) {
			chunks.push(Buffer.from(chunk));
		}

		const rawBody = Buffer.concat(chunks);

		// Parse multipart manually to avoid h3's array limits
		const [, boundary] = contentType.split("boundary=");
		if (!boundary) {
			throw createError({
				statusCode: 400,
				message: "Invalid multipart boundary"
			});
		}

		return parseMultipartManually(rawBody, boundary);
	} catch (error) {
		logger.error("Error parsing multipart data:", error);
		throw createError({
			statusCode: 400,
			message: "Failed to parse multipart form data"
		});
	}
}

/**
 * Parse multipart form data manually to avoid h3's array length limits
 */
function parseMultipartManually(
	body: Buffer,
	boundary: string
): Array<{ name: string; data: Buffer; filename?: string }> {
	const parts: Array<{ name: string; data: Buffer; filename?: string }> = [];
	const boundaryBuffer = Buffer.from(`--${boundary}`);
	const endBoundary = Buffer.from(`--${boundary}--`);

	let pos = 0;
	while (pos < body.length) {
		// Find next boundary
		const boundaryIndex = body.indexOf(boundaryBuffer, pos);
		if (boundaryIndex === -1) {
			break;
		}

		// Check if this is the end boundary
		if (body.slice(boundaryIndex, boundaryIndex + endBoundary.length).equals(endBoundary)) {
			break;
		}

		// Move past the boundary and CRLF
		pos = boundaryIndex + boundaryBuffer.length;
		if (body[pos] === 0x0d && body[pos + 1] === 0x0a) {
			pos += 2;
		}

		// Find the end of headers (double CRLF)
		const headersEnd = body.indexOf(Buffer.from("\r\n\r\n"), pos);
		if (headersEnd === -1) {
			break;
		}

		// Parse headers
		const headersStr = body.subarray(pos, headersEnd).toString("utf-8");
		const nameMatch = headersStr.match(/name="([^"]+)"/);
		const filenameMatch = headersStr.match(/filename="([^"]+)"/);

		if (!nameMatch?.[1]) {
			pos = headersEnd + 4;
			continue;
		}

		// Find the data start and end
		const dataStart = headersEnd + 4;
		const nextBoundary = body.indexOf(Buffer.from(`\r\n--${boundary}`), dataStart);
		const dataEnd = nextBoundary === -1 ? body.length : nextBoundary;

		// Extract the data
		const data = body.slice(dataStart, dataEnd);

		parts.push({
			name: nameMatch[1],
			data,
			filename: filenameMatch ? filenameMatch[1] : undefined
		});

		pos = dataEnd;
	}

	return parts;
}
```

**Comment by productdevbook** [comment]
@pi0 This is labeled v1. In v2, `readMultipartFormData` is deprecated (exists only in `_deprecated.ts` as a thin wrapper around native `event.req.formData()`). The old custom multipart parser is gone — file size handling is delegated to the platform's native FormData implementation + `assertBodySize()`.

Can this be closed as not applicable to v2?

**Comment by pi0** [comment]
I think we should think about better multipart support for v2.

**Comment by productdevbook** [comment]
@pi0 Here's an analysis of the current state and what "better multipart support for v2" could look like:

## Current State

v2 delegates entirely to native `event.req.formData()` — runtime-portable (Node/Bun/Deno/CF Workers), but **buffers the entire body in memory** before any part is accessible.

The only size protection is `assertBodySize` / `bodyLimit`, which operates on the total request body with no per-file granularity.

## What's Missing

1. **Streaming multipart parsing** — no way to process parts as they arrive without buffering the entire body. A 1GB upload = 1GB in heap before the handler runs.

2. **Per-part size limits** — `bodyLimit` checks total body, but can't enforce "max 10MB per file" or "max 5 files".

3. **Per-part MIME validation** — no utility to check file types before buffering content.

4. **Pipe-to-destination** — no way to stream a file part directly to disk/S3/storage without buffering.

## Possible v2 API Ideas

### Option A: `readMultipartStream()` — low-level async iterable

```ts
app.post("/upload", async (event) => {
  for await (const part of readMultipartStream(event)) {
    // part.name, part.filename, part.type available before reading body
    if (part.filename) {
      // Stream directly to storage
      await part.body.pipeTo(storageWritable);
    } else {
      // Small text field — buffer it
      const value = await part.text();
    }
  }
});
```

### Option B: `readFormData()` with options — pragmatic enhancement

```ts
const formData = await readFormData(event, {
  maxFileSize: 10 * 1024 * 1024,  // 10MB per file
  maxFiles: 5,
  maxFields: 20,
  allowedTypes: ["image/*", "application/pdf"],
});
```

### Option C: Both — layered API

- `readMultipartStream(event, opts?)` for streaming use cases
- Enhanced `readFormData(event, opts?)` for simple use cases with validation

## Implementation Considerations

- The boundary-parsing transform is non-trivial (cross-chunk boundary detection). Options:
  - Depend on an external lib (e.g., `busboy`, `@mjackson/multipart-parser`)
  - Minimal built-in parser (consistent with h3's "minimal core" philosophy)
  - Use a peer dependency pattern (like `crossws`)

- h3 already has the right primitives: `event.req.body` is a `ReadableStream`, `EventStream` shows the streaming pattern, `defineHandler` shows the factory pattern.

What direction are you thinking? Happy to prototype whichever approach you prefer.
